export const CABANG_GROUPS: Record<string, string[]> = {
  "Kantor Pusat & Wilayah": [
    "Kantor Pusat BSG",
    "Kantor Wilayah BSG Gorontalo"
  ],
  "Kantor Cabang (KC)": [
    "Cabang Utama",
    "Cabang Airmadidi",
    "Cabang Amurang",
    "Cabang Bitung",
    "Cabang Boroko",
    "Cabang Calaca",
    "Cabang Gorontalo",
    "Cabang Jakarta",
    "Cabang Kawangkoan",
    "Cabang Kotamobagu",
    "Cabang Limboto",
    "Cabang Lolak",
    "Cabang Malang",
    "Cabang Marisa",
    "Cabang Melonguane",
    "Cabang Ratahan",
    "Cabang Surabaya",
    "Cabang Tahuna",
    "Cabang Tilamuta",
    "Cabang Tomohon",
    "Cabang Tondano",
    "Cabang Tutuyan",
    "KC Kwandang",
    "KC Molibagu",
    "KC Siau",
    "KC Suwawa"
  ],
  "Kantor Cabang Pembantu (KCP)": [
    "KCP Bahu",
    "KCP Beo",
    "KCP Cempaka Putih",
    "KCP Kelapa Gading",
    "KCP Langowan",
    "KCP Likupang",
    "KCP Lirung",
    "KCP Manembo-Nembo",
    "KCP Modoinding",
    "KCP Mopuya",
    "KCP Motoling",
    "KCP Paguyaman",
    "KCP Paguat",
    "KCP Pancoran",
    "KCP Pasar Segar Paal Dua",
    "KCP Pasar Sentral",
    "KCP Popayato",
    "KCP Randangan",
    "KCP Ranotana",
    "KCP Sam Ratulangi",
    "KCP Tagulandang",
    "KCP Tamako",
    "KCP Telaga",
    "KCP Tolangohula",
    "KCP Tuminting"
  ],
  "Lainnya": [
    "Other"
  ]
};
